// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PizzaHut.Core.Entities;

public partial class TblGender
{
    public int GenderId { get; set; }

    public string GenderName { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}