// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PizzaHut.Core.Entities;

public partial class TrackActivityLog
{
    public int LogId { get; set; }

    public string UserName { get; set; }

    public string ControllerName { get; set; }

    public string ActionName { get; set; }

    public int? ExecutionTimeMs { get; set; }

    public DateTime? Timestamp { get; set; }

    public string Message { get; set; }
}